apiVersion: v1
kind: Service
metadata:
  name: plus-poc-app-stg
spec:
  type: NodePort
  selector:
    app: plus-poc-app-stg
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30048
